version: 2.1

orbs:
    aws-cli: circleci/aws-cli@1.3.0

jobs:
    build_project:
        working_directory: ~/devops-days-in-baku-2020-demo-app
        docker:
            - image: node:10.15.3
        steps:
            - checkout
            - run:
                name: Installing dependencies
                command: yarn
            - run:
                name: Building project
                command: yarn build
            - persist_to_workspace:
                root: .
                paths:
                    - .
    deploy_project:
        executor: aws-cli/default
        steps:
            - attach_workspace:
                at: .
            - aws-cli/setup:
                profile-name: default
            - run:
                name: Upload file to S3
                command: aws s3 sync ./ s3://devops-days-in-baku-2020-demo-app.s3.eu-central-1.amazonaws.com --delete

workflows:
    version: 2
    build:
        jobs:
            - build_project:
            - deploy_project:
                requires:
                    - build_project
                context: MY_CONTEXT